require 'src/constants'
MAP = {}
OVERWORLD_MAP_WIDTH = 10
OVERWORLD_MAP_HEIGHT = 10
MAP_WIDTH = 10
MAP_HEIGHT = 8
---[[

for x = 1, OVERWORLD_MAP_HEIGHT do
    table.insert(MAP, {})
    for y = 1, OVERWORLD_MAP_WIDTH do
        table.insert(MAP[x], {})
    end
end
--]]


for x = 1, OVERWORLD_MAP_HEIGHT do
    for y = 1, OVERWORLD_MAP_WIDTH do
        for z = 1, 80 do
            MAP[x][y][z] = SAND
        end
    end
end

---[[
MAP[1][1] = {
    FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST,
    FIRST, SECOND, THIRD, FOURTH, FIFTH, SIXTH, SEVENTH, EIGHTH, NINTH, FIRST,
    FIRST, FIRST, FIRST, FIRST, FIFTH, SIXTH, SEVENTH, EIGHTH, FIRST, FIRST,
    FIRST, FIRST, FIRST, FIRST, FIFTH, SIXTH, SEVENTH, EIGHTH, FIRST, FIRST,
    FIRST, FIRST, FIRST, FIRST, FIFTH, SIXTH, SEVENTH, EIGHTH, FIRST, FIRST,
    FIRST, FIRST, FIRST, FOURTH, FIFTH, SIXTH, SEVENTH, EIGHTH, SIXTH, FIRST,
    FIRST, FIRST, FIRST, FOURTH, FIFTH, SIXTH, SEVENTH, EIGHTH, SIXTH, FIRST,
    FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST, FIRST
}
--]]

--MAP[1][1] = {1, 2}

MAP[1][2] = {
    SECOND  , SECOND, SECOND, SECOND, SECOND, SECOND, SECOND, SECOND, SECOND, SECOND,
    SECOND  , FOURTH, THIRD, FOURTH, FIFTH, SECOND, SEVENTH, EIGHTH, NINTH, SECOND,
    SECOND  , FOURTH, THIRD, NINTH, FIFTH, SECOND, SEVENTH, EIGHTH, NINTH, SECOND,
    SECOND  , FOURTH, THIRD, NINTH, FIFTH, SECOND, SEVENTH, EIGHTH, NINTH, SECOND,
    SECOND  , FOURTH, THIRD, NINTH, FIFTH, SECOND, SEVENTH, EIGHTH, NINTH, SECOND,
    SECOND  , FOURTH, THIRD, FOURTH, FIFTH, SECOND, SEVENTH, EIGHTH, SIXTH, SECOND,
    SECOND  , FOURTH, THIRD, FOURTH, FIFTH, SECOND, SEVENTH, EIGHTH, SIXTH, SECOND,
    SECOND  , SECOND, SECOND, SECOND, SECOND, SECOND, SECOND, SECOND, SECOND, SECOND
}

MAP[2][1] = {
    THIRD  , THIRD, THIRD, THIRD, THIRD, THIRD, THIRD, THIRD, THIRD, THIRD,
    THIRD  , FOURTH, THIRD, FOURTH, FIFTH, THIRD, SEVENTH, EIGHTH, NINTH, THIRD,
    THIRD  , FOURTH, THIRD, NINTH, FIFTH, THIRD, SEVENTH, EIGHTH, NINTH, THIRD,
    THIRD  , FOURTH, THIRD, NINTH, FIFTH, THIRD, SEVENTH, EIGHTH, NINTH, THIRD,
    THIRD  , FOURTH, THIRD, NINTH, FIFTH, THIRD, SEVENTH, EIGHTH, NINTH, THIRD,
    THIRD  , FOURTH, THIRD, FOURTH, FIFTH, THIRD, SEVENTH, EIGHTH, SIXTH, THIRD,
    THIRD  , FOURTH, THIRD, FOURTH, FIFTH, THIRD, SEVENTH, EIGHTH, SIXTH, THIRD,
    THIRD  , THIRD, THIRD, THIRD, THIRD, THIRD, THIRD, THIRD, THIRD, THIRD
}
